// Bureau/tropical-medical/frontend/src/views/Profil.vue
<script setup>
import { ref } from 'vue';
import AppLayout from '../components/AppLayout.vue';
import { api } from '../utils/api';
import { useAuthStore } from '../stores/auth';

const auth = useAuthStore();
const error = ref('');
const success = ref('');
const saving = ref(false);

const pwForm = ref({ ancien: '', nouveau: '', confirm: '' });

const changePassword = async () => {
  if (pwForm.value.nouveau !== pwForm.value.confirm) {
    error.value = 'Les mots de passe ne correspondent pas';
    return;
  }
  saving.value = true; error.value = ''; success.value = '';
  try {
    await api.put('/auth/password', { ancien: pwForm.value.ancien, nouveau: pwForm.value.nouveau });
    success.value = 'Mot de passe modifié avec succès';
    pwForm.value = { ancien: '', nouveau: '', confirm: '' };
  } catch (e) { error.value = e.message; } finally { saving.value = false; }
};
</script>

<template>
  <AppLayout>
    <div class="max-w-lg space-y-5">
      <h2 class="text-2xl font-bold text-gray-900">Mon profil</h2>

      <div class="card">
        <div class="flex items-center gap-4 mb-5">
          <div class="w-16 h-16 rounded-2xl bg-green-100 flex items-center justify-center text-green-700 font-bold text-2xl">
            {{ auth.user?.prenom?.[0] }}{{ auth.user?.nom?.[0] }}
          </div>
          <div>
            <div class="text-xl font-bold text-gray-900">{{ auth.user?.prenom }} {{ auth.user?.nom }}</div>
            <div class="text-sm text-gray-500">{{ auth.user?.email }}</div>
            <div class="badge badge-green mt-1">{{ auth.user?.role }}</div>
          </div>
        </div>
        <div class="grid grid-cols-2 gap-4 text-sm">
          <div><span class="text-gray-500">Téléphone</span><div class="font-medium mt-1">{{ auth.user?.telephone }}</div></div>
          <div><span class="text-gray-500">Compte créé</span><div class="font-medium mt-1">{{ new Date(auth.user?.created_at).toLocaleDateString('fr') }}</div></div>
        </div>
      </div>

      <div class="card">
        <h3 class="font-semibold text-gray-900 mb-4">Changer le mot de passe</h3>
        <form @submit.prevent="changePassword" class="space-y-3">
          <div><label class="text-sm font-medium text-gray-700">Mot de passe actuel</label>
            <input v-model="pwForm.ancien" type="password" required class="input mt-1" /></div>
          <div><label class="text-sm font-medium text-gray-700">Nouveau mot de passe</label>
            <input v-model="pwForm.nouveau" type="password" required minlength="6" class="input mt-1" /></div>
          <div><label class="text-sm font-medium text-gray-700">Confirmer</label>
            <input v-model="pwForm.confirm" type="password" required class="input mt-1" /></div>
          <div v-if="error" class="text-sm text-red-600 bg-red-50 rounded px-3 py-2">{{ error }}</div>
          <div v-if="success" class="text-sm text-green-600 bg-green-50 rounded px-3 py-2">{{ success }}</div>
          <button type="submit" :disabled="saving" class="btn btn-primary">{{ saving ? '...' : 'Modifier' }}</button>
        </form>
      </div>
    </div>
  </AppLayout>
</template>

// Bureau/tropical-medical/frontend/src/pages/Profil.jsx
import { useState } from 'react';
import { useAuth }   from '../context/AuthContext';
import { authService } from '../services/auth.service';
import Card   from '../components/ui/Card';
import Button from '../components/ui/Button';
import Avatar from '../components/ui/Avatar';

const inp = {
  padding: '0.7rem 0.95rem',
  border: '1.5px solid var(--border)',
  borderRadius: '10px',
  fontSize: '0.92rem',
  width: '100%',
  outline: 'none',
  background: 'var(--surface2)',
  color: 'var(--text)',
  transition: 'border-color .2s',
};
const lbl = {
  fontSize: '0.78rem', fontWeight: '700', color: 'var(--muted)',
  display: 'block', marginBottom: '0.3rem',
};

const ROLE_LABELS = {
  medecin: 'Médecin',
  patient: 'Patient',
  receptionniste: 'Réceptionniste',
  pharmacien: 'Pharmacien',
  admin: 'Administrateur',
};

export default function Profil() {
  const { user, setUser } = useAuth();

  const [form, setForm] = useState({
    nom:       user?.nom       || '',
    prenom:    user?.prenom    || '',
    telephone: user?.telephone || '',
    email:     user?.email     || '',
    mot_de_passe_actuel:  '',
    nouveau_mot_de_passe: '',
    confirm_mdp:          '',
  });
  const [saving,  setSaving]  = useState(false);
  const [success, setSuccess] = useState('');
  const [error,   setError]   = useState('');

  const sf = (k) => (e) => setForm(f => ({ ...f, [k]: e.target.value }));
  const focus = (e) => { e.target.style.borderColor = 'var(--g)'; };
  const blur  = (e) => { e.target.style.borderColor = 'var(--border)'; };

  const submit = async (e) => {
    e.preventDefault();
    setError(''); setSuccess('');

    if (form.nouveau_mot_de_passe && form.nouveau_mot_de_passe !== form.confirm_mdp) {
      setError('Les deux mots de passe ne correspondent pas');
      return;
    }

    setSaving(true);
    try {
      const payload = {
        nom: form.nom, prenom: form.prenom,
        telephone: form.telephone, email: form.email,
      };
      if (form.nouveau_mot_de_passe) {
        payload.mot_de_passe_actuel  = form.mot_de_passe_actuel;
        payload.nouveau_mot_de_passe = form.nouveau_mot_de_passe;
      }
      await authService.updateProfile(payload);
      setSuccess('Profil mis à jour avec succès');
      setForm(f => ({ ...f, mot_de_passe_actuel: '', nouveau_mot_de_passe: '', confirm_mdp: '' }));
      if (setUser) setUser(u => ({ ...u, nom: form.nom, prenom: form.prenom }));
    } catch (err) {
      setError(err.response?.data?.error || 'Erreur lors de la mise à jour');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div style={{ padding: '1.5rem', maxWidth: '560px', margin: '0 auto' }}>
      <h2 style={{ fontSize: '1.4rem', color: 'var(--text)', marginBottom: '1.5rem' }}>Mon profil</h2>

      {/* Avatar + rôle */}
      <Card style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1.5rem', padding: '1.25rem' }}>
        <Avatar name={`${form.prenom} ${form.nom}`} size={56} />
        <div>
          <p style={{ fontWeight: '800', fontSize: '1.05rem', color: 'var(--text)' }}>
            {form.prenom} {form.nom}
          </p>
          <p style={{ fontSize: '0.82rem', color: 'var(--muted)', marginTop: '0.1rem' }}>
            {ROLE_LABELS[user?.role] || user?.role}
          </p>
        </div>
      </Card>

      {success && (
        <div style={{ background: '#e8f5e9', color: '#2e7d32', padding: '0.75rem 1rem', borderRadius: '10px', marginBottom: '1rem', fontSize: '0.88rem', fontWeight: '600' }}>
          ✓ {success}
        </div>
      )}
      {error && (
        <div style={{ background: '#fde8e8', color: '#c0392b', padding: '0.75rem 1rem', borderRadius: '10px', marginBottom: '1rem', fontSize: '0.88rem', fontWeight: '600' }}>
          ⚠ {error}
        </div>
      )}

      <form onSubmit={submit}>
        <Card style={{ padding: '1.25rem', marginBottom: '1rem' }}>
          <p style={{ fontWeight: '700', color: 'var(--text)', marginBottom: '1rem', fontSize: '0.95rem' }}>
            Informations de contact
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.85rem' }}>
            <div>
              <label style={lbl}>Prénom</label>
              <input value={form.prenom} onChange={sf('prenom')} required style={inp} onFocus={focus} onBlur={blur} />
            </div>
            <div>
              <label style={lbl}>Nom</label>
              <input value={form.nom} onChange={sf('nom')} required style={inp} onFocus={focus} onBlur={blur} />
            </div>
            <div>
              <label style={lbl}>Téléphone</label>
              <input value={form.telephone} onChange={sf('telephone')} style={inp} onFocus={focus} onBlur={blur} />
            </div>
            <div>
              <label style={lbl}>Email</label>
              <input type="email" value={form.email} onChange={sf('email')} style={inp} onFocus={focus} onBlur={blur} />
            </div>
          </div>
        </Card>

        <Card style={{ padding: '1.25rem', marginBottom: '1.25rem' }}>
          <p style={{ fontWeight: '700', color: 'var(--text)', marginBottom: '0.4rem', fontSize: '0.95rem' }}>
            Changer le mot de passe
          </p>
          <p style={{ fontSize: '0.8rem', color: 'var(--muted)', marginBottom: '1rem' }}>
            Laissez vide si vous ne souhaitez pas changer de mot de passe.
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            <div>
              <label style={lbl}>Mot de passe actuel</label>
              <input type="password" value={form.mot_de_passe_actuel} onChange={sf('mot_de_passe_actuel')}
                style={inp} onFocus={focus} onBlur={blur} autoComplete="current-password" />
            </div>
            <div>
              <label style={lbl}>Nouveau mot de passe</label>
              <input type="password" value={form.nouveau_mot_de_passe} onChange={sf('nouveau_mot_de_passe')}
                style={inp} onFocus={focus} onBlur={blur} autoComplete="new-password" />
            </div>
            <div>
              <label style={lbl}>Confirmer le nouveau mot de passe</label>
              <input type="password" value={form.confirm_mdp} onChange={sf('confirm_mdp')}
                style={inp} onFocus={focus} onBlur={blur} autoComplete="new-password" />
            </div>
          </div>
        </Card>

        <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
          <Button type="submit" disabled={saving}>
            {saving ? 'Enregistrement…' : 'Sauvegarder les modifications'}
          </Button>
        </div>
      </form>
    </div>
  );
}
